name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Ubuntu
            os: ubuntu-latest
          - name: Windows
            os: windows-latest

    name: ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Install Ninja
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          curl -L -o ninja-linux.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip
          unzip ninja-linux.zip -d bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Configure
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DRTRB_BUILD_TESTS=ON 

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

  miri:
    name: Miri

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Miri
        uses: dtolnay/rust-toolchain@miri        

      - name: Test
        run: cargo miri test