name: Release

on:
  release:
    types: [published]

# The GITHUB_TOKEN needs permission to upload to the release.
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package
        run: tar -cvf rtrb-src.tar.gz include/ src/ Cargo.lock Cargo.toml CMakeLists.txt LICENSE

      - name: Upload
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: gh release upload ${{github.event.release.tag_name}} rtrb-src.tar.gz